apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - image: dyotamo/cache:1.0.2
          name: cache
          resources:
            limits:
              memory: "64Mi"
              cpu: "0.5"
          env:
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:7
          name: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
